# Generated by Django 5.2.9 on 2026-02-05 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_orderitem_product_orderitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.TextField(choices=[('PND', 'Pending'), ('PAID', 'Paid'), ('CND', 'Cancled')], default='PND'),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
