# Generated by Django 5.2.9 on 2026-03-10 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productdetail_delete_productdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='porductspecifications',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productstock',
            name='product',
        ),
        migrations.AddField(
            model_name='porductspecifications',
            name='product_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_specification', to='products.productdetail'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='products.productdetail'),
        ),
        migrations.AddField(
            model_name='productstock',
            name='product_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_stock', to='products.productdetail'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_image_front', to='products.product'),
        ),
    ]
