# Generated by Django 5.2.9 on 2026-03-10 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_porductspecifications_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='porductspecifications',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
